# Generated by Django 4.2.3 on 2023-07-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_play_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.actor'),
        ),
        migrations.AlterField(
            model_name='play',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='plays', to='theatre.genre'),
        ),
    ]
